on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  NODE_MAJOR_VERSION: "24"

jobs:
  build-test-publish:
    name: "CI/CD Pipeline"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup Node"
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_MAJOR_VERSION }}
          cache: "npm"

      - name: "Setup :: Installation"
        run: npm install

      - name: "Application :: Type Checking"
        run: npm run tc

      - name: "Application :: Build"
        run: npm run build

      - name: "Application :: Test"
        run: npm test

      - name: "Publish to NPM"
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public
          npm config delete //registry.npmjs.org/:_authToken
